### ISSUE TITLE
`panic: too many field items: 3` when using schema-qualified table names in `WHERE`

### ISSUE THREAD

**Issue by jack-hughes** [sqlc-dev/sqlc#2948]
### Version

1.23.0

### What happened?

When running `sqlc generate` on a large number of queries i intermittently get the following error: `panic: too many field items: 3`

Same with `sqlc vet`. The code is not generate, even when the error does not occur.

### Relevant log output

```shell
panic: too many field items: 3

goroutine 6 [running]:
github.com/sqlc-dev/sqlc/internal/compiler.(*Compiler).resolveCatalogRefs(0xc00053be40?, 0xc0005c2360, {0xc00076b240, 0x6, 0x2379c40?}, {0xc0005db8c0, 0x3, 0x23f1240?}, 0xc0005c2240, {0x0, ...})
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/compiler/resolve.go:177 +0x5474
github.com/sqlc-dev/sqlc/internal/compiler.(*Compiler)._analyzeQuery(0xc000421200, 0x1?, {0xc00054560d, 0x517}, 0x1)
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/compiler/analyze.go:189 +0xd7f
github.com/sqlc-dev/sqlc/internal/compiler.(*Compiler).analyzeQuery(...)
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/compiler/analyze.go:110
github.com/sqlc-dev/sqlc/internal/compiler.(*Compiler).parseQuery(0xc000421200, {0x28ef3a0?, 0xc000379c80}, {0xc000544000, 0x1b25}, {{0x0, 0x0, {0x0, 0x0}, 0x0, ...}})
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/compiler/parse.go:101 +0x5b5
github.com/sqlc-dev/sqlc/internal/compiler.(*Compiler).parseQueries(0xc000421200, {{0x0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}})
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/compiler/compile.go:81 +0x492
github.com/sqlc-dev/sqlc/internal/compiler.(*Compiler).ParseQueries(...)
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/compiler/engine.go:76
github.com/sqlc-dev/sqlc/internal/cmd.parse({_, _}, {_, _}, {_, _}, {{0x0, 0x0}, {0xc00032bca0, 0xa}, ...}, ...)
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/cmd/generate.go:369 +0x2eb
github.com/sqlc-dev/sqlc/internal/cmd.Generate.func1()
	/home/jack/go/pkg/mod/github.com/sqlc-dev/sqlc@v1.23.0/internal/cmd/generate.go:238 +0x77e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/jack/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/home/jack/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:72 +0x96
```

### Playground URL

https://play.sqlc.dev/p/dd3ccf067ae733ea1deb83e075affb585aaebc6d0484f538c64fa28aec1b4972

**Comment by andrewmbenton** [comment]
Which database engine are you using? The fact that this is intermittent is really odd. Do you see this when adding or editing a particular query? Maybe something using `sqlc.slice()`?

This wouldn't be related to the number of queries. It looks like there are two places in `resolveCatalogRefs()` where this can happen. It's possibly related to an `IN` or `LIKE` clause but without seeing at least an offending query fragment it's unlikely we'll be able to debug.

**Comment by jack-hughes** [comment]
@andrewmbenton 

DB Engine: PostgreSQL

When commenting out these three queries, it works:


```
-- name: GetTotalSlackQueries :one
SELECT
    COUNT(*) AS count
FROM astoria.slack_feedback
WHERE astoria.slack_feedback.workspace_id = $1
AND created_at BETWEEN $2::date AND $3::date;

-- name: GetTotalSlackQueriesResolved :one
SELECT
    COUNT(*) AS count
FROM astoria.slack_feedback
WHERE astoria.slack_feedback.workspace_id = $1
  AND (issue_raised = false OR issue_raised IS NULL)
  AND created_at BETWEEN $2::date AND $3::date;

-- name : GetTotalSlackQueriesRequestsCreated :one
SELECT
    COUNT(*) AS count
FROM astoria.tickets
WHERE astoria.tickets.workspace_id = $1
  AND source = 'RAISED_FROM_BOT'::ticket_source
  AND created_at BETWEEN $2::date AND $3::date;
```

**Comment by jack-hughes** [comment]
Looks like it was the table names: `astoria.tickets.workspace_id`. Never mind.

**Comment by andrewmbenton** [comment]
I am assuming `astoria` is a schema name, and that `tickets` is a table and `workspace_id` is a column. If so then I am pretty sure that your queries are valid and sqlc shouldn't panic.

So it seems like this is a bug, and I will reopen but probably rename.

**Comment by jack-hughes** [comment]
> I am assuming `astoria` is a schema name, and that `tickets` is a table and `workspace_id` is a column. If so then I am pretty sure that your queries are valid and sqlc shouldn't panic.
> 
> So it seems like this is a bug, and I will reopen but probably rename.

Correct. Thanks!
